3월 18일 - 브루트 포스
Altu-Bitu-2/Altu-Bitu-2_Algorithm pull request #6
Opened 2022-03-24 02:57 UTC by dlvcoth

#### 내용 & 질문
> [1018] 보드 col이 홀수로 주어질때 결과값이 제대로 안 나오는데, 왜 그런지 못 찾았습니다. 
[10757] 결과값이 맞는데, 왜 백준에서 틀렸는지 모르겠습니다.

#### <기존 제출>
> 1018,1759,2503,2798,10757

#### <추가 제출>
>

2022-03-24 15:48 UTC, bsa0322 requested changes
p1. 과제 하시느라 너무 수고하셨습니다 ! 코멘트가 늦어서 죄송해요 ㅜㅜ 질문주신 부분에 대한 답변 아래에 남겼습니다 🥰 힌트 더 필요하시면 말씀해주세요 ~! 수정하시거나 질문 있으실  때 언제든 저 불러주세요~! 수고하셨습니다~!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1018.cpp
> +        i++,j++;
현재 i와 j를 같이 늘려주고 있네요! 그렇다면 모든 경우를 검사하지 못하고 대각선만 검사하게 되겠죠? 😉

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1018.cpp
> +    return min(cnt,64-cnt); //(BW~형식일때 바꿔야할 갯수)+(WB형식일때 ~) = 64개로 일정하므로
하나만 구해서 64에서 빼주신 거 아주 좋아요~~!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1018.cpp
> +    }
p2. 입력을 char로 받고 있으니 board의 자료형도 char로 맞춰주는 게 좋을 것 같아요~! 더불어 char로 하나씩 받는 방법도 있지만, 행 자체를 string으로 받아버려도 공백 입력을 처리할 수 있답니다 😉

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1018.cpp
> +    }
p2. 체스판을 미리 생성해주셨네요! 이 방법도 너무 좋지만, 지금 찾아주신 규칙을 활용해서 바로 비교해볼 수도 있을 것 같아요! 🥰 더불어 짝수 행과 홀수 열, 홀수 행과 짝수 열의 공통점을 찾아주시면 규칙도 더 간결하게 줄일 수 있답니다. 생각이 안나신다면 아래 힌트 참고해주세요!

<details>
<summary>Hint</summary>
<div markdown="1">
&nbsp;&nbsp;&nbsp;&nbsp;행과 열을 더해볼까요!
</div>
</details>

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/10757.cpp
> +    for (int i=max(A.size(), B.size())-1; i>=-1;i--){
p1. 인덱스 에러 가능성이 있는 코드네요!! for문의 조건값을 주의해서 볼까요!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/10757.cpp
> +
현재, i값을 A와 B중 더 긴 사이즈의 마지막 인덱스부터 검사해주고 있는데요! 해당 인덱스는 자릿수가 더 작은 수에선 접근을 할 수가 없겠죠. 하지만 일의 자리부터 더해줘야 하기 때문에 둘 다 접근이 가능해야 해요! 즉, 지금 자릿수가 다를 경우의 처리가 잘 이루어지지 않고 있습니다!!

일의 자리부터 더하면서, 길이가 더 긴 것을 기준으로 돌릴 수 있게 하려면 먼저 일의 자리가 앞으로 오게 하거나, 아니면 아예 A와 B의 마지막 인덱스를 따로 변수로 관리해서 사용해줘도 좋을 것 같아요 🥰 힌트 더 필요하시면 말씀해주세요~!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1759.cpp
> +    }
p2. C를 다시 사용한다면 새로운 변수 c를 만들어서 while문을 사용하는 것보다 for문을 써주는 편이 더 효율적이예요~! 더불어 c++에서 변수 이름은 스네이크표기법에 따라 소문자로 생성해주셔야 합니다! 🥰

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1759.cpp
> +    }
p2. 마찬가지로 for문을 사용해주시는 편이 더 좋을 것 같습니다~!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1759.cpp
> +        cryptoSet.insert(crypto); //4. Set에 넣어 string 간 정렬
p1. 우선 함수화도 너무 잘 해주시고, 로직도 좋은데요!! 미리 무언가 처리를 해주면 암호를 만들면서 sort와 set 사용 없이 바로 저장해줄 수 있어요~! set은 삽입에 시간복잡도가 O(logN)이나 들기도 하니 오름차순 정렬을 위해서라면 사용해주지 않는 편이 좋습니다! 
현재 조합으로 암호를 만들어가고 있어요. 그러면 조합에 따라 만들어지는 암호는 **기존의 배열 순서대로** 겠죠! 그렇다면 만들어진 암호를 오름차순으로 하기 위해선 어디서 무엇을 해주어야 할까요? 조합을 만들기 전 미리 처리되어야 할 것 같아요 😉

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/1759.cpp
> +        else cnt_consonant++;
p2. 모음의 개수만으로 자음의 개수를 알 수 있는 방법이 있어요! 우리는 암호의 전체 길이를 알고 있죠. 😉
더불어 모음을 미리 map이나 배열에 저장해놓고 검사해줘도 좋아요~!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/2503.cpp
> +        }
볼을 계산할 때 위치가 다른지도 봐줘야겠죠! 😊

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/2503.cpp
> +    }
p1. set의 순환 중에 set의 원소를 삭제하게 되면, 순환에 문제가 생겨 에러가 납니다! 새로운 set에 저장하는 방식으로 풀어주시거나, 아니면 배열을 사용해서 true/ false 값을 저장해주셔도 좋을 것 같아요 😊

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/2798.cpp
> +    }
p3. input받아서 넣어주는 것도 좋지만, 미리 크기를 선언하고 받아도 좋을 것 같아요~!

2022-03-24 15:48 UTC, bsa0322 commented on 3월 18일 브루트 포스/2798.cpp
> +
p2. 가장 작은 차이를 구해줘도 좋지만, 사실 3개 고른 카드의 합이 m보다 작거나 같아야 한다는 것을 활용해서 가장 가까이에 있는 값을 쉽게 찾을 수 있어요! 세 카드를 더한 값이  m보다 작거나 같다면, 그 카드들 중 m과 가장 가까운 카드는 어떻게 구할 수 있을까요?

2022-03-24 22:58 UTC, dlvcoth commented on 3월 18일 브루트 포스/10757.cpp
> +    for (int i=max(A.size(), B.size())-1; i>=-1;i--){
이거 각 숫자를 reverse 함수 적용해서 1의자리를 앞쪽으로 바꿔주고,
    for (int i=0; i<max(A.size(), B.size());i++){
...
        **if (i<A.size())** result+=A[i]-'0';
이런식으로 처리해줘도 인덱스 에러가 날까요? 
저는 혹시라도 '없는 인덱스' 접근하는 경우는 저if문에서 알아서 걸러줬을거라고 생각했어서
괜찮을 줄 알았거든요..!!

2022-03-25 16:05 UTC, jaeseo222 commented on 3월 18일 브루트 포스/10757.cpp
> +    for (int i=max(A.size(), B.size())-1; i>=-1;i--){
네 맞아요! 너무 잘 접근해주셨습니다!!🤗🤗

2022-03-25 16:06 UTC, jaeseo222 commented
최종적으로 필수 2문제, 선택 3문제 확인했습니다!
머지해주셔도 됩니다 ! 감사합니다 🥰🥰

2022-03-26 03:06 UTC, bsa0322 commented on 3월 18일 브루트 포스/10757.cpp
> +    for (int i=max(A.size(), B.size())-1; i>=-1;i--){
넵 잘 접근해주셨습니다! 🥰 제가 처음에 인덱스 에러를 언급드린 부분은 i 가 -1까지 접근해서 그런 거였어요!! 😉

2022-03-26 05:13 UTC, merged